on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Linux build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.8" }
                    - { os: ubuntu-latest, py: "3.9" }
                    - { os: ubuntu-latest, py: "3.10" }
                    - { os: ubuntu-latest, py: "3.11" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir Cython
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  pip install .[dev]
            - name: PKG-TEST
              run: |
                  python3 -m pytest . -n 4